### PR TITLE
Remove particles involving view model when deploying a new weapon

### PR DESCRIPTION
**Pull request by TomyLobo**
This fixes the "Cannot update control point 1 for effect 'muzzleflash_pistol/smg/rifle/shotgun'" message spam on the client.

### CODE REVIEW

**Comment by BSVino** [comment]
Nice one! I procrastinated finding that shit for years.

**Comment by BSVino** [comment]
But yea I'm sure it's fine ship it.

**Comment by TomyLobo** [comment]
Already shipped it anyway :)

**Comment by TomyLobo** [comment]
This didn't fix the issue entirely, but the spam is down to half a page on very rare occasions. I think it still happens if you die and there are still particles.

**Comment by TomyLobo** [comment]
I implemented another fix and I drilled down to a layer of even weirder bugs... I think I fixed it this time :)

I get rare instances of these:
````
Model '(null)' doesn't have attachment 'muzzle' to attach particle system 'muzzleflash_pistol' to.
Cannot update control point -1 for effect 'muzzleflash_pistol'.
Cannot update control point 1 for effect 'tracer_bullet'.
````

**Pull request merged**
