### PR TITLE
Delay map change until the current vote concludes

### LINKED ISSUE #121: Map ends before the last vote concludes
If a vote is started shortly before or during intermission, the game doesn't wait until the vote concludes, but instead switches to the new map, ignoring votes cast so far.

What makes this a common issue is that if there's an overtime, the nextlevel vote for the map is delayed until the overtime concludes, which is exactly when intermission begins.

### PR DESCRIPTION
**Pull request by TomyLobo**
This delays a map change until after a vote completes

Fixes #121

### CODE REVIEW

**Comment by TomyLobo** [comment]
Tested this with Dementei and it works.

**Comment by TomyLobo** [comment]
The changes from #122, #123, #125 and #126 are up on the "develop" beta branch.

**Comment by BSVino** [comment]
Why did you invert the logics? Did that fix any issue? I'm concerned about introducing bugs.

**Comment by TomyLobo** [comment]
I inverted the logic mainly for two reasons:
1. I like it better that way :)
2. I would have otherwise had to add another layer around it in order to keep with the old style

Inverting the logic didn't fix any issues.
If you look at these commits in isolation, with whitespace changes hidden, it should be obvious that they are neutral.

Both of the changes follow the following scheme:
```C++
code1;

if (cond1) {
    cond2;
}

return;
```
`||`
`\/`
```C++
code1;

if (!cond1)
    return;

code2;

return;
```

**Comment by BSVino** [comment]
Okay, trusting you didn’t break anything!

**Pull request merged**
