### PR TITLE
Disable the overflow weapon drop mechanism by default

### LINKED ISSUE #93: Add a cvar to control pickup behaviour
`cl_pickup_dropweapons 0|1`
default: 1
0 - Do not drop weapons in order to accomodate weapons picked up from the ground.
1 - Drop weapons in order to accomodate weapons picked up from the ground.

### PR DESCRIPTION
**Pull request by TomyLobo**
Can be re-enabled by setting da_drop_overflow_on_pickup to 1.

I'm open to debate about the default value.
I'm also looking for a way to make a GUI option for this (and da_slide_unclick_time).

Fixes #93

### CODE REVIEW

**Comment by TomyLobo** [comment]
Yes, that was intended.
I think the new behaviour is better, since it doesn't force you to go through a bunch of dropped guns on the floor while you're being shot at, in order to find the gun you just accidentally autodropped :)

If someone desparately wants the old behaviour, they can use the cvar.
If someone just sometimes wants to grab a gun from the ground while they're full, they can easily drop one of their guns.

**Comment by TomyLobo** [comment]
Rebased

**Comment by TomyLobo** [comment]
Hmm, I can pop up a notice on how to drop weapons if you hit the limit.

**Comment by TomyLobo** [comment]
Rebased again

**Comment by BSVino** [comment]
I'd have to see a design.

**Comment by TomyLobo** [comment]
How's this? :)
image

**Comment by BSVino** [comment]
Include in that same panel the key to drop, e.g. "Inventory Full \n [G] Drop Weapon" and I think I'm OK with that.

**Comment by TomyLobo** [comment]
Gotta figure out how that works first :)

**Comment by TomyLobo** [comment]
Turns out you can just use "%drop%" in a hint message and the client will replace it accordingly:
image

**Pull request merged**
