### PR TITLE
Weapon sounds now work on dedicated servers

### PR DESCRIPTION
**Pull request by voxelizedworld**
Co-authored-by: Joshua Ashton <joshua@froggi.es>

### CODE REVIEW

**Comment by TomyLobo** [comment]
We tested this and got double sounds.
When we tested the release version, we still had the regular sounds.
I think there's some randomness involved, or maybe some buildup.

**Comment by TomyLobo** [comment]
Well it took 3 people to fix it :)

**Review by TomyLobo — APPROVED** [review]
Last commit developed in pair programming with @voxelizedworld, rest looks ok to me and we successfully tested it.

**Review by BSVino — COMMENTED** [review]
Can't tell what went wrong from a naive reading of the code, but it looks like you folks tested pretty thoroughly and it plausibly works, so approved.

**Pull request merged**
