### PR TITLE
Drop briefcase when leaving active state

### PR DESCRIPTION
**Pull request by TomyLobo**
Thanks to @FaceMan-THE for reporting this bug.

### CODE REVIEW

**Comment by BSVino** [comment]
Maybe it should be done when exiting the player active state instead? Or as well?

**Comment by TomyLobo** [comment]
@BSVino That's the better solution, yeah. Doing both doesn't seem necessary.

**Comment by TomyLobo** [comment]
That's a nice state system in there. Did you make it or did it come with the SDK?

**Comment by BSVino** [comment]
Nah that was Valve. Ship it.

**Pull request merged**
