### PR TITLE
Don't waste slowmo time

### PR DESCRIPTION
**Pull request by TomyLobo**
This can happen when doing a stunt kill during slowmo and then trying to turn off slowmo.

<sub>This PR contains the same cleanup commit as my other PRs (#29 and #30).</sub>

### CODE REVIEW

**Comment by TomyLobo** [comment]
Btw, I didn't test this patch since I don't have the build environment set up yet.
I have to set myself up with a VM first, lest that visual studio express litter my system

**Comment by BSVino** [comment]
Wow I'm surprised to be getting a PR after all this time. Happy to see that someone cares.

Unfortunately we've just announced that we're finishing production on this game with 1.2. Also, I don't have a development environment for it anymore so I can't check this PR. So I'm not sure if I can take it.

**Comment by Marocco2** [comment]
It's only a file change

**Comment by TomyLobo** [comment]
Can't @Black-Stormy check it?

**Comment by TomyLobo** [comment]
Now that I have my development environment set up, I was able to test it.
I was able to:
- reproduce the issue on the latest master
- confirm that my patch fixes it
- find another related bug (slowmo seconds get overwritten instead of added to when deactivating slowmo)
- fix that related bug

I amended my commit by the fix and also added a change that is relevant for people trying to invoke the batch files on windows after checking them out on cygwin.

**Comment by TomyLobo** [comment]
I also figured out why the unstucker (da_auto_unstick) doesn't work in multiplayer.
I'm developing a fix and I'll post that as a separate PR.

**Comment by TomyLobo** [comment]
Shuffled some stuff around and created the other PR I was talking about.

**Comment by Black-Stormy** [comment]
Hey, thanks for the bugfixes! I haven't been able to get my build to compile properly so I don't have a sufficiently clean environment to test in either, but I'll be happy to push your build to the dev branch on steam for testing.

In other news, feel free to poke around my commits and see if you can get any of that stuff working, it would be nice to have achievements, and if you can get it going I'll push it to steam.

**Comment by TomyLobo** [comment]
After what I learned from creating my dev env, I think the following steps should work:
* Make Steam download the dev branch of the game and the "Source SDK Base 2013 Multiplayer" Tool
* Clone this repo
* Copy the "dab", "bin" and "da_info" directories from ``Steam\SteamApps\common\Double Action`` into the cloned repo's checkout at ``mp\game``
* Go to ``mp\src`` directory in explorer
* Edit ``creategameprojects.bat`` and change "2013" to "2010"
* Run ``creategameprojects.bat``
* In theory, vpc should generate a .sln file, but in my case, it didn't.
* Open VS2010 and add the following project files to a new solution:
    * game\client\client_da.vpc
    * datanetworking\datanetworking.vpc
    * materialsystem\stdshaders\game_shader_dx9_da.vpc
    * mathlib\mathlib.vpc
    * raytrace\raytrace.vpc
    * game\server\server_da.vpc
    * tier1\tier1.vpc
    * vgui2\vgui_controls\vgui_controls.vpc
* Open the properties (Right-click -> Properties) of the Client (DA) project, go to Configuration Properties -> Debugging and set the following values:
    
    | Key               | Value                                                                            |
    |-------------------|----------------------------------------------------------------------------------|
    | Command           | D:\path\to\Steam\SteamApps\common\Source SDK Base 2013 Multiplayer\hl2.exe       |
    | Command Arguments | -allowdebug -dev -sw -game "D:\path\to\DoubleAction\mp\game\dab" +map da_cocaine |
    | Working Directory | D:\path\to\Steam\SteamApps\common\Source SDK Base 2013 Multiplayer               |

* Open the project dependencies (Right-click -> Project Dependencies...) of the Client (DA) project and check everything

Now F5 should prompt you to build everything and then run it.

**Comment by BSVino** [comment]
Email me: bs.vino@gmail.com

**Comment by TomyLobo** [comment]
I need to close and remake this PR in order to retarget it at the ``develop`` branch.

**Pull request closed without merging**
